package com.tylerdev.stonks.data.remote.api

import com.tylerdev.stonks.BuildConfig
import okhttp3.ResponseBody
import retrofit2.http.GET
import retrofit2.http.Query

/**
 * Retrofit contract for the Alpha Vantage stock data service.
 *
 * Declares the HTTP endpoints used to fetch market listing data. Implementations are generated by
 * Retrofit at runtime; repositories call [getListings] and parse the returned [ResponseBody] into
 * domain models.
 */
interface StockApi {
    companion object {
        const val BASE_URL = "https://alphavantage.co"
    }

    /**
     * Fetches the full set of active and delisted stock symbols.
     *
     * @param apiKey Alpha Vantage API key used to authenticate the request.
     * @return Raw CSV payload containing symbol, name, exchange, asset type, and listing status.
     */
    @GET("query?function=LISTING_STATUS")
    suspend fun getListings(@Query("apikey") apiKey: String = BuildConfig.ALPHA_VANTAGE_API_KEY): ResponseBody
}