package com.tylerdev.stonks.data.remote.api

import com.tylerdev.stonks.BuildConfig
import com.tylerdev.stonks.data.remote.dto.CompanyInfoDto
import okhttp3.ResponseBody
import retrofit2.http.GET
import retrofit2.http.Query

/**
 * Retrofit contract for the Alpha Vantage stock data service.
 *
 * Declares HTTP endpoints for listings, intraday prices, and company overview data. Implementations
 * are generated by Retrofit at runtime; repositories call these methods and map responses into
 * domain models.
 */
interface StockApi {
    companion object {
        const val BASE_URL = "https://alphavantage.co"
    }

    /**
     * Fetches hourly intraday price data for the given symbol.
     *
     * @param symbol Ticker symbol to query (e.g. AAPL).
     * @param apiKey Alpha Vantage API key used to authenticate the request.
     * @return Raw CSV time series with timestamp, OHLC, and volume columns.
     */
    @GET("query?function=TIME_SERIES_DAILY&datatype=csv")
    suspend fun getIntradayInfo(
        @Query("symbol") symbol: String,
        @Query("apikey") apiKey: String = BuildConfig.ALPHA_VANTAGE_API_KEY
    ): ResponseBody

    /**
     * Fetches company profile and fundamental overview data for the given symbol.
     *
     * @param symbol Ticker symbol to query (e.g. AAPL).
     * @param apiKey Alpha Vantage API key used to authenticate the request.
     * @return Deserialised overview payload mapped to [CompanyInfoDto].
     */
    @GET("query?function=OVERVIEW")
    suspend fun getCompanyInfo(
        @Query("symbol") symbol: String,
        @Query("apikey") apiKey: String = BuildConfig.ALPHA_VANTAGE_API_KEY
    ): CompanyInfoDto
}